using ImarcAdmin.Models;

namespace ImarcAdmin.Services;

public sealed class PostEditorStateService
{
    private readonly SlugService _slugService;
    private readonly FrontMatterService _frontMatterService;

    public PostEditorStateService(SlugService slugService, FrontMatterService frontMatterService)
    {
        _slugService = slugService;
        _frontMatterService = frontMatterService;
    }

    public void Initialize(EditablePost post)
    {
        if (!post.IsNew)
        {
            post.LastAutoGeneratedSlug = string.Empty;
            return;
        }

        if (string.IsNullOrWhiteSpace(post.LastAutoGeneratedSlug))
        {
            post.LastAutoGeneratedSlug = post.Slug;
        }

        UpdateNewPostPermalink(post);
    }

    public void ApplyTitleChange(EditablePost post, string? title)
    {
        post.Title = title ?? string.Empty;
        if (!post.IsNew)
        {
            return;
        }

        if (string.IsNullOrWhiteSpace(post.Slug) || string.Equals(post.Slug, post.LastAutoGeneratedSlug, StringComparison.Ordinal))
        {
            var nextAutoSlug = _slugService.Slugify(post.Title);
            post.Slug = nextAutoSlug;
            post.LastAutoGeneratedSlug = nextAutoSlug;
        }

        UpdateNewPostPermalink(post);
    }

    public void ApplySlugChange(EditablePost post, string? slug)
    {
        if (post.SlugLocked)
        {
            return;
        }

        post.Slug = string.IsNullOrWhiteSpace(slug)
            ? string.Empty
            : _slugService.Slugify(slug);
        if (post.IsNew)
        {
            UpdateNewPostPermalink(post);
        }
    }

    public void ApplyDateChange(EditablePost post, string? date)
    {
        post.PublishDate = date ?? post.PublishDate;
        if (post.IsNew)
        {
            UpdateNewPostPermalink(post);
        }
    }

    private void UpdateNewPostPermalink(EditablePost post)
    {
        if (!post.IsNew)
        {
            return;
        }

        var slugForPermalink = string.IsNullOrWhiteSpace(post.Slug)
            ? post.LastAutoGeneratedSlug
            : post.Slug;

        post.Permalink = string.IsNullOrWhiteSpace(slugForPermalink)
            ? string.Empty
            : _frontMatterService.BuildPermalink(post.PublishDate, slugForPermalink);
    }
}
