name: Build & Deploy Eleventy to GitHub Pages

# ← This section tells Actions *when* to run
on:
  push:
    branches:
      - main          # run on every push to `main`
  workflow_dispatch:  # also allow you to trigger it manually from the UI

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm ci

      - name: Build with Eleventy
        run: npx @11ty/eleventy --input=src --output=public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public